# Generated by Django 2.2.28 on 2023-03-10 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0004_auto_20230307_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('subject', models.CharField(choices=[('general', 'General'), ('math', 'Math'), ('english', 'English'), ('computing', 'Computing'), ('physics', 'Physics')], default='general', max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Flash Card Sets',
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('answer_text', models.CharField(max_length=500)),
                ('flash_card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.FlashCardSet')),
            ],
        ),
    ]
