# Generated by Django 2.2.28 on 2023-03-15 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0005_flashcard_flashcardset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='card.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='flashcardtest',
            name='flash_card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.FlashCardSet'),
        ),
        migrations.AddField(
            model_name='flashcardtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='flash_card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.FlashCardSet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
