# Generated by Django 2.2.28 on 2023-03-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20230315_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardset',
            name='category',
        ),
    ]
